---
abstract: 'Lego part object.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lego-Part
no_index:
  directory:
    - inc
    - t
requires:
  Class::Utils: 0.03
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: '0.01'
